### ISSUE TITLE
Does support PHP extension on windows?

### ISSUE THREAD

**Issue by hamedsbt** [djondb/djondb_php#1]
We are looking for **very very high performance document-store DB** for our sophisticated web application on windows host, can you release PHP extension on windows please?!

Thank you!

**Comment by crossleyjuan** [comment]
Hello, no problem, I'll have it ready by the end of the week, the php driver is one of the few left to be ported as native code, I'll have it ready if that helps you.

**Comment by crossleyjuan** [comment]
@hamedsbt  the djondb php native driver is now ready, just follow the instructions, let's us know if you need anything else.

**Comment by crossleyjuan** [comment]
Documentation updated
